### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AndiLavera** [andrewc910/manjaro-eos#7]
# Roadmap
This spin is not aiming to a 1:1 of Elementary OS. I prefer the Pantheon DE and plan to keep it. I prefer Elementary apps and plan to keep those as well. However, I have interests in flatpak, wayland & mobile and will be thinking about those a lot which will influence the direction. This is all conjecture until I can dedicate more time to this project along with talking this out with others to ensure a proper feature scope & direction.

# Bugs & Fixes
- [ ] Fix Ibus not autostarting
- [ ] Fix Picture In Picture shadow

# Flatpak
- [ ] Install as many base apps as flatpaks as possible
  - [ ] Fork manjaro-tools & create method to install packages as flatpaks like you can do with snaps
- [ ] Switchboard plug for flatpak permissions (Maybe work with the elementary OS team on this one)

# Wayland
- [ ] I would like to get away from X11 but this one may be a pipe dream for now.
